### ISSUE TITLE
Your build process is not very good.

### ISSUE THREAD

**Issue by friesofdoom** [fribidi/fribidi#104]
Ever tried building this on Windows? Neither meson nor mingw have managed to build this on windows.  You don't even supply a configure script, you only supply the script to build the configure script.

**Comment by tp-m** [comment]
If you have any particular problem with the Meson build on Windows, please post details about setup and output / errors in a separate issue, thanks.

**Comment by dov** [comment]
FriBidi (as a lot of other free software) was designed and implemented by volunteers that each had his own reason for contributing. If there is some feature missing that you need, you are always contribute it on your own, or perhaps hire someone to implement it. That's how free software works. That said, the more specific and polite you are in error reporting, the bigger chance there is that someone might pick up the bait and help you solve the issue.

**Comment by friesofdoom** [comment]
Thanks, I apologize. I was in a fit of rage when I posted that.
