### ISSUE TITLE
using xz instead of bzip2 for release tarball

### ISSUE THREAD

**Issue by vtorri** [fribidi/fribidi#108]
hello

bzip2 compresses less than xz. Using xz will help downloading faster fribidi

It is quite easy to modify this with autotools

thank you

**Comment by dov** [comment]
Please send a pull request.

**Comment by vtorri** [comment]
https://www.gnu.org/software/automake/manual/automake.html#The-Types-of-Distributions

replace in configure.ac : 
AM_INIT_AUTOMAKE([1.11.1 gnits dist-bzip2 no-dist-gzip -Wall no-define])
with
AM_INIT_AUTOMAKE([1.11.1 gnits dist-xz no-dist-gzip -Wall no-define])

do you really want a PR for such a simple thing ?

**Comment by dov** [comment]
Thanks. That should be enough. :-)

**Comment by vtorri** [comment]
PR #131

**Comment by vtorri** [comment]
fixed in 03efbdd491cbd50fdf4b2defba205b0816d703fa
