### ISSUE TITLE
Symbolic link in tarball breaks on some systems

### ISSUE THREAD

**Issue by bradleysepos** [fribidi/fribidi#114]
See https://github.com/HandBrake/HandBrake/issues/2014.

Ideally, the symlink README would simply be replaced with a plain text file of the same name with the contents, "See README.md".

**Comment by vtorri** [comment]
+1 as i'm also on Windows, where symlink like unix ones do not exist

**Comment by bradleysepos** [comment]
It seems a new release has been tagged without this fix.

@dov Is there anything we can do to fast track this? It breaks tarball extraction on non-*nix systems such as MSYS2/Windows.

**Comment by dov** [comment]
I will have to quickly do another release as I forgot to update the meson file (I should create a check list). Any chance of getting a pull request that fixes this issue?

**Comment by bradleysepos** [comment]
@dov Done, see PR #123. Thank you.

**Comment by vtorri** [comment]
@dov add this check list in the git repo :-)
