### ISSUE TITLE
FRIBIDI_ENTRY not correctly defined on Windows

### ISSUE THREAD

**Issue by vtorri** [fribidi/fribidi#128]
on Windows, FRIBIDI_ENTRY  is not correctly defined.

first, you don't consider building with mingw-w64. instead of

defined(_MSC_VER)

you should use

defined(_WIN32)

to target all Windows compilers

The usual scheme to define such macro is : 
 * if the library is built
   * if shared : set it to __declspec(dllexport)
   * if static, set it to nothing
 * otherwise set it to __declspec(dllimport)

so something like that could be used (using what libtool is defining):

```
#ifdef _WIN32
# ifdef FRIBIDI_BUILD
#  ifdef DLL_EXPORT
#   define FRIBIDI_ENTRY __declspec(dllexport)
#  else
#   define FRIBIDI_ENTRY
#  endif
# else
#  define FRIBIDI_ENTRY __declspec(dllimport)
# endif
#else
# ifdef __GNUC__
#  if __GNUC__ >= 4
#   define FRIBIDI_ENTRY __attribute__ ((visibility("default")))
#  else
#   define FRIBIDI_ENTRY
#  endif
# else
#  define FRIBIDI_ENTRY
# endif
#endif
```

where FRIBIDI_BUILD is defined only when building the library
DLLEXPORT is defined by libtool to specify that the shared lib is built. This is easy to port to meson

the unix part is there to support visibility feature

see https://gcc.gnu.org/wiki/Visibility for reference

**Comment by vtorri** [comment]
no comment on this ?

**Comment by tp-m** [comment]
Note that `FRIBIDI_ENTRY` also gets defined/set from the `meson.build` file. (Not saying anything is right or wrong, just pointing it out.)

**Comment by vtorri** [comment]
indeed, thank you for the reminder ! I'm waiting other comments

**Comment by dov** [comment]
I'm personally not using fribidi on Windows, so I'll be happy to receive a PR for this.

**Comment by vtorri** [comment]
see PR #138
please check on unix

**Comment by dov** [comment]
Thanks! Checked on Linux and merged the pull request.
