### ISSUE TITLE
converting "\uFEE0\uFE8E" to the "\uFEFC\uFEFF" while reording the text via fribidi

### ISSUE THREAD

**Issue by Dizgah** [fribidi/fribidi#132]
Hi there,

I'm using Fribidi for reordering my texts before displaying it on my embedded device.
For some special characters like"\uFE8D\uFEE3\uFEE0\uFE8E\FB8e"//املاک
which contain "\uFEE0\uFE8E"// ل+ا
it convert these specific characters to the "\uFEFC\uFEFF" لا+zero width space
which cause some problems to me.
How could I order to preventing from this replacements?
this is how  use Fribidi:

```
stat =  fribidi_log2vis(
/* input */
utf16Buf,
tmpLen,
&pbase_dir,
/* output */
reorderedStr,
NULL,
NULL,
NULL);
```

**Comment by dov** [comment]
If you don't want shaping (ligature substitution, etc), then catch the `positions_L_to_V` output of `fribidi_log2vis` and do the reordering on your own. 

Btw, you are likely to get better answers from the fribidi mailing list, then on github.
