### ISSUE TITLE
Building fribidi using meson on windows 

### ISSUE THREAD

**Issue by mohamed-hatem** [fribidi/fribidi#133]
i am using meson to build fribidi as a static lib on windows , i have vs 2017 installed , but when i try to build the project using this command : meson build --default-library=static -Ddocs=false --backend=vs
i get this error  LINK : fatal error LNK1104: cannot open file 'kernel32.lib'

log file :
Build started at 2019-12-17T03:03:04.842538
Main binary: C:\Users\adam\AppData\Local\Programs\Python\Python38-32\python.exe
Build Options: -Ddocs=false -Dbackend=vs -Ddefault_library=static
Python system: Windows
The Meson build system
Version: 0.52.999
Source dir: C:\projects\fribidi
Build dir: C:\projects\fribidi\build
Build type: native build
Project name: fribidi
Project version: 1.0.8
No CFLAGS in the environment, not changing global flags.
No LDFLAGS in the environment, not changing global flags.
No CPPFLAGS in the environment, not changing global flags.
Sanity testing C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx86\x86\cl.exe
Is cross compiler: False.
Sanity check compiler command line: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx86\x86\cl.exe C:\projects\fribidi\build\meson-private\sanitycheckc.c /FeC:\projects\fribidi\build\meson-private\sanitycheckc.exe /MDd /nologo /showIncludes /link
Sanity check compile stdout:
sanitycheckc.c
LINK : fatal error LNK1104: cannot open file 'kernel32.lib'

-----
Sanity check compile stderr:

-----

meson.build:1:0: ERROR: Compiler C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx86\x86\cl.exe can not compile programs.

**Comment by tp-m** [comment]
This looks more like a meson bug or an environment/setup issue.

Are you doing this from the "Native Tools Command Prompt for VS2017"?

Does it work for a simple hello world C program?

Have you tried the latest Meson release? (you're using git, is that right?)

I have tried this with vs2019 and meson 0.51.2 and it seems to work fine for me.

**Comment by mohamed-hatem** [comment]
yes i am using the developer cmd for vs 2017 

my meson version is 0.52.999

i've tried to do the simple hello world example and i got the same error as before

**Comment by tp-m** [comment]
It sounds like it's a Meson bug then, best to file it against Meson or pop into the Meson IRC channel `#mesonbuild` on the FreeNode network.

**Comment by mohamed-hatem** [comment]
ok thanks will do that , in the mean time is there another way to build fribidi on windows

**Comment by tp-m** [comment]
Yes, you should be able to build it with the default backend (which is `ninja`).

**Comment by mohamed-hatem** [comment]
downgrading  meson to version 0.51.2 didn't solve the issue , and when i tried using ninja it gave this error :
**ninja: error: loading 'build.ninja': The system cannot find the file specified.**

**Comment by mohamed-hatem** [comment]
are there any other options to build the project on windows?

**Comment by mohamed-hatem** [comment]
what version of python are u using

**Comment by tp-m** [comment]
Python 3.7.4 in my case.

**Comment by vtorri** [comment]
@mohamed-hatem on Windows, i usually compile fribidi with MSYS2 + mingw-w64

**Comment by mohamed-hatem** [comment]
i solved the problem by creating a Cmake file for the fribidi project which created a vs solution

**Comment by jmckenna** [comment]
@mohamed-hatem can you share your cmake files?  This would be an excellent addition to Windows/Visual Studio people trying to compile fribidi.  Thanks!

**Comment by jmckenna** [comment]
For the record, here was my working steps (so other Visual Studio people can follow someday):

- open Visual Studio command prompt
- make sure Python3 executable is found within your PATH
- execute:
   ```
    python -m pip install meson
  ```
- create /build directory inside fribidi root
- at fribidi root, execute: 
  ```
   meson build --buildtype=release --default-library=both -Ddocs=false --backend=vs2017
  ```
  - for the full list of build options see: https://mesonbuild.com/Builtin-options.html
- cd into /build
- execute: 
  ```
    meson compile
  ```
- output is in: /build/lib/

Hope that helps someone someday.
