### ISSUE TITLE
Removal of fribidi_log2vis_get_embedding_levels breaks other software

### ISSUE THREAD

**Issue by aelmahmoudy** [fribidi/fribidi#134]
In https://github.com/fribidi/fribidi/commit/d569512f20a9ad940b81bbac85f055b07729d760, the fribidi_log2vis_get_embedding_levels got removed, causing an ABI break.
I realize that the manpage of this function still exists in documentation.

See: https://bugs.debian.org/947081

**Comment by dov** [comment]
Fixed in commit c4d0f2f . Indeed this function was removed by mistake.
