### ISSUE TITLE
1.0.8 removed fribidi_log2vis_get_embedding_levels()

### ISSUE THREAD

**Issue by ppisar** [fribidi/fribidi#137]
1.0.8 removed fribidi_log2vis_get_embedding_levels() from the library. This breaks ABI. The change was introduced with d569512f20a9ad940b81bbac85f055b07729d760 commit. Please note that the function is still declared in fribidi-deprecated.h.

Either it was a mistake and it should be reverted, or the soname of the library should be bumped, the declaration removed from the header file and all occurrences removed from a documentation.

**Comment by dov** [comment]
Duplicate of  #134 . It has already been fixed in master.
