### ISSUE TITLE
Commit (Merge pull request #138: fix FRIBIDI_ENTRY value on Windows) breaks mingw cross-compilation under Linux

### ISSUE THREAD

**Issue by ctrlesc** [fribidi/fribidi#139]
Commit 7c155c64ea91d9ad3a25cdf35c904e4cb2484448 (Merge pull request #138: fix FRIBIDI_ENTRY value on Windows) breaks mingw cross-compilation under Linux halting with the errors that follow.  This problem does not occur after reverting to f503e576c8345dd32d7438569346d6ca9aa50044.
The path to ld is omitted below for clarity (/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld:).
```
  CCLD     fribidi.exe
fribidi-main.o:fribidi-main.c:(.text.startup+0x215): undefined reference to `__imp_fribidi_set_debug'
fribidi-main.o:fribidi-main.c:(.text.startup+0x2e3): undefined reference to `__imp_fribidi_parse_charset'
fribidi-main.o:fribidi-main.c:(.text.startup+0x2fa): undefined reference to `__imp_fribidi_char_set_desc'
fribidi-main.o:fribidi-main.c:(.text.startup+0x31c): undefined reference to `__imp_fribidi_char_set_title'
fribidi-main.o:fribidi-main.c:(.text.startup+0x342): undefined reference to `__imp_fribidi_parse_charset'
fribidi-main.o:fribidi-main.c:(.text.startup+0x35c): undefined reference to `__imp_fribidi_set_mirroring'
fribidi-main.o:fribidi-main.c:(.text.startup+0x368): undefined reference to `__imp_fribidi_set_reorder_nsm'
fribidi-main.o:fribidi-main.c:(.text.startup+0x381): undefined reference to `__imp_fribidi_get_bidi_type'
fribidi-main.o:fribidi-main.c:(.text.startup+0x4b0): undefined reference to `__imp_fribidi_charset_to_unicode'
fribidi-main.o:fribidi-main.c:(.text.startup+0x53f): undefined reference to `__imp_fribidi_log2vis'
fribidi-main.o:fribidi-main.c:(.text.startup+0x71a): undefined reference to `__imp_fribidi_remove_bidi_marks'
fribidi-main.o:fribidi-main.c:(.text.startup+0x954): undefined reference to `__imp_fribidi_unicode_to_charset'
fribidi-main.o:fribidi-main.c:(.text.startup+0xc8c): undefined reference to `__imp_fribidi_char_set_desc'
fribidi-main.o:fribidi-main.c:(.text.startup+0xc93): undefined reference to `__imp_fribidi_char_set_title'
fribidi-main.o:fribidi-main.c:(.text.startup+0xcb5): undefined reference to `__imp_fribidi_char_set_name'
fribidi-main.o:fribidi-main.c:(.text.startup+0xcf1): undefined reference to `__imp_fribidi_version_info'
fribidi-main.o:fribidi-main.c:(.text.startup+0xd56): undefined reference to `__imp_fribidi_char_set_name'
```

Steps to reproduce:
autoreconf -fiv
./configure --prefix="/home/user/build" --host="x86_64-w64-mingw32" --enable-static --disable-shared
make

**Comment by vtorri** [comment]
i've compiled like that with autotools on Windows. I'll try cross compilation on linux today or tomorrow.

**Comment by vtorri** [comment]
the problem is that when we *use* the fribidi library, __declspec(dllimport) is always used, which is not correct.

question : if we build both static and shared library of fribidi, should we link the binary against the shared of static library ?

for me, static lib on Windows is not the way to go and we should build only shared library

**Comment by tp-m** [comment]
Or guard the `dllimport` with an additional `#if !defined(FRIBIDI_STATIC_COMPILATION)` ? That way it would still be *possible* to do so. I think linking to the shared lib by default makes sense too.

**Comment by vtorri** [comment]
@tp-m i've already written something like that, but that mean a lot more stuff to write, both on autotools and meson sides.

we should also have 2 pc file, one for static lib, one for shared lib

Which advantages do we have to have static lib ?

**Comment by ctrlesc** [comment]
> Which advantages do we have to have static lib ?

Just wanted to say thanks for considering this.  Without getting into a huge debate regarding the pros & cons of static vs dynamic linking, it is really a convenience/packaging issue especially with inexperienced users.  You just provide them one monolithic executable, and it's guaranteed to run.  In my context, I am cross compiling ffmpeg with many options and really want to having to manage the dozens of associated DLLs.

**Comment by dov** [comment]
Did you reach any consensus on this? I just fixed an algorithm bug in FriBidi and would like to create another release. Should I revert #138 ?

**Comment by vtorri** [comment]
@dov for now, revert it, i'll try to find some time for a more complete patch

**Comment by vtorri** [comment]
@dov btw do you plan to keep 2 build systems ?

**Comment by dov** [comment]
> @dov for now, revert it, i'll try to find some time for a more complete patch

Will do.

> @dov btw do you plan to keep 2 build systems ?

I don't have any strong opinion about it. I realized that meson is certainly superior, but I don't have enough experience to ascertain that it is sufficient for all platforms. And until it bothers someone sufficiently to persuade me to drop automake, I'll just leave it as it is.

**Comment by egorpugin** [comment]
I've been hit by this also, but now on linux.
I build with visibility hidden and FRIBIDI_ENTRY=attribute visibility.
But fribidi code assumes that FRIBIDI_ENTRY must carry extern.
I think it is not right.

Code must differ from VISIBILITY API like (FRIBIDI_ENTRY, SOME_LIBRARY_API etc.) from such thing like extern decl.
So, I propose:
1) Remove `extern` from `FRIBIDI_ENTRY` and fix all places that must be extern.
2) Restore dllexport/dllimport pair under all such defs.
3) Keep `#ifndef FRIBIDI_ENTRY` around all those ifdefs to make user able to add his own logic.

**Comment by vtorri** [comment]
extern must be used for variables that are parts of the API
i willl try to fix FRIBIDI_ENTRY this week

**Comment by egorpugin** [comment]
> extern must be used for variables that are parts of the API

Please move it from FRIBIDI_ENTRY and specify explicitly near vars.

**Comment by vtorri** [comment]
@ctrlesc can you please apply this patch and see if it works for you. I've tested and it seems it is working here
[fribidi.diff.gz](https://github.com/fribidi/fribidi/files/4708212/fribidi.diff.gz)

**Comment by ctrlesc** [comment]
> @ctrlesc can you please apply this patch and see if it works for you. I've tested and it seems it is working here
> [fribidi.diff.gz](https://github.com/fribidi/fribidi/files/4708212/fribidi.diff.gz)

I applied the patch to 436453435423311ec496957d8fc4cdb52c8f9fdf and verified it with git diff to make sure it was correctly applied.  I still get the same undefined reference errors when running the same build commands.

**Comment by vtorri** [comment]
sorry, i've not tested this case. Patch git tree again with this diff :

[fribidi.diff.gz](https://github.com/fribidi/fribidi/files/4717743/fribidi.diff.gz)

**Comment by vtorri** [comment]
btw, you should try meson, it's so fast compared to autotools

**Comment by ctrlesc** [comment]
> sorry, i've not tested this case. Patch git tree again with this diff :
> 
> [fribidi.diff.gz](https://github.com/fribidi/fribidi/files/4717743/fribidi.diff.gz)

Good news, mostly :) The autotools cross-compile now builds, and I tested the meson cross as well (yes, it is fast).  Both generate a working fribidi.exe and libfribidi.a, but the visibility declaration needed for a static cross-compile isn't quite right when I am trying to link against the lib.  I can get both build methods to work with your latest patch by forcing:

`FRIBIDI_ENTRY __attribute__ ((visibility("default")))`

at line 65 of fribidi-common.h.  I think you need to you need to work out the defines for FRIBIDI_STATIC (or possibly something like FRIBIDI_LIB_STATIC to only build the lib and ignore the exe) to prevent other builds from potentially breaking.

Again, thanks for addressing this.  It looks like we are much closer now.

**Comment by vtorri** [comment]
I will use FRIBIDI_LIB_STATIC

about `FRIBIDI_ENTRY __attribute__ ((visibility("default")))`, this is for non Windows OS, I guess. Because although setting `__attribute__ ((visibility("default")))`  throws only a warning on Windows, it has no effect on this OS.

**Comment by vtorri** [comment]
@ctrlesc so ?

**Comment by ctrlesc** [comment]
Apologies, but I did not realize you were waiting on a response.  With the last patch you provided and the addition of the visibility attribute, I think it works.  You might want to guard it with with 
`#if defined (__GNUC__) && (__MINGW32__)`
as this should fix the warnings you mentioned when complied under Windows/MSVC.

**Comment by vtorri** [comment]
with PR #145 , i've compiled with meson and autotools both shared and static lib. I've tested with an example the static and shared libraries. The exemple runs smoothly

**Comment by vtorri** [comment]
no problem here. I've applied the 2 diff separately, thank you !

**Comment by ctrlesc** [comment]
Note to users when linking against libfribidi statically, PR-145 adds the prerprocessor define FRIBIDI_LIB_STATIC which needs to be defined for the files that rely on the Fribidi the API.
