### ISSUE TITLE
FriBidi (fribidi_log2vis) can not handle emoji codepoints

### ISSUE THREAD

**Issue by Rickodesea** [fribidi/fribidi#149]
When the string contains emoji, the function 'fribidi_log2vis' crashes.  
* Example string: "Hello World! It's تشرفت بمقابلتك 😀😄😆😍!".
* FriBidi version : 0.19.7
* Platform: Linux(Ubuntu)
* Valgrind Output: Process terminating with default action of signal 11 (SIGSEGV)
==7382==  Bad permissions for mapped region at address 0x4AF31BE
==7382==    at 0x5ADC9C0: fribidi_get_bidi_types (in /usr/lib/x86_64-linux-gnu/libfribidi.so.0.3.6)
==7382==    by 0x5ADCF0E: fribidi_log2vis (in /usr/lib/x86_64-linux-gnu/libfribidi.so.0.3.6)

**Comment by Rickodesea** [comment]
Realised the error.  I was passing UTF-8 codepoints but the function expected UTF-16 codepoints.

**Comment by khaledhosny** [comment]
The input and output of this function is `FriBidiChar` array, which is `uint32_t` and should be UTF-32 code units (passing to it UTF-16 code will be broken for surrogate pairs, which is common for Emoji).
