### ISSUE TITLE
mingw-w64 cross compiling fails

### ISSUE THREAD

**Issue by JohannesKauffmann** [fribidi/fribidi#158]
I'm trying to cross-compile fribidi using mingw-w64 on Ubuntu 20.04.1. Cloned the latest [master](https://github.com/fribidi/fribidi/commit/c75a94c84ad1c7d3a3df89b42370933976f4ba59) at time of writing and ran the following:
`autoreconf -fiv`
`./configure --enable-static --host=x86_64-w64-mingw32 --prefix=/usr/x86_64-w64-mingw32/`
`make`

This generated a warning in the configure script [output](https://pastebin.com/CMyMK0jW) about the host triplet. Weird. However, more importantly, the make command fails trying to run an .exe file. Is there anything obvious I'm doing wrong here?

**Comment by barndawgie** [comment]
I'm able to do it as follows (from current Master or release 1.0.9) using Ubuntu 20.04 running on WSL 2.0:
```bash
./autogen.sh --host=x86_64-w64-mingw32 --prefix=/home/barndawgie/dev/ffmpeg-cross-compile-script/ffmpeg_install --enable-static --disable-shared
make -j 2
```

**Comment by JohannesKauffmann** [comment]
Thanks, I can confirm that indeed works!
