### ISSUE TITLE
fribidi_log2vis wasm?

### ISSUE THREAD

**Issue by jfuehner** [fribidi/fribidi#178]
Hi! I am new to using FriBidi and had a few questions...

I have a use-case where I do not know if the text I am receiving is in logical or visual order. Can the `fribidi_log2vis` convenience function detect whether a string is already is in logical or visual order and return the appropriate visual order? If not would there be a way to achieve this capability using the library? Would you have a javascript/wasm example for this?

In looking at this [example](https://harfbuzz.github.io/harfbuzzjs/fribidi) it is not clear to me the numerical values represent that are populated in the `resultElement`. 

Thanks!

**Comment by dov** [comment]
Hi Jason,

No, it is impossible to detect whether a string is in logical or visual
order. You might be able to cook up some of language related heuristic, but
it will probably fail for too often to be useful. E.g. in Hebrew there are
words that have another meaning backwards (E.g. a queue TOR (Taf Vav Resh)
vs the name ROT (Ruth) (Resh Vav Taf)). Given a single word string you
can't determine which meaning it is and whether it is in logical or visual
order.

Regards,
Dov

**Comment by jfuehner** [comment]
Thanks for that Dov. Very helpful.

Would you have an JavaScript WASM example of using the fribidi_log2vis function
you could share?

**Comment by dov** [comment]
fribidi is written in C. There is no javascript or wasm binding that is part of this project. So perhaps you should ask who ever wrote the binding. That said, you are of course welcome to look at the source code, which includes examples of how to use the log2vis api from C. Regarding the link you gave, the numbers appear to be are embedding levels. I suggest that you refer to the Unicode standard UAX#9 to understand the meaning of those.

**Comment by jfuehner** [comment]
Apologies I thought the FriBidi was associated with harfbuzz.
