### ISSUE TITLE
Use ICU, UCDN to provide Unicode properties needed by FriBidi

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [fribidi/fribidi#19]

**Comment by KrasnayaPloshchad** [comment]
With this support FriBidi will be able to handle BiDi functionality for all scripts included in Unicode, that is what HarfBuzz does anyway.

**Comment by dov** [comment]
FriBidi currently uses and parses on its own the unicode data as published at ftp://ftp.unicode.org/Public/UNIDATA/ . Why isn't this enough? What functionality are you missing? Please file bugs for specific failures instead of suggesting adding dependencies on external libraries.

**Comment by khaledhosny** [comment]
I don’t think there is anything here to fix. Should be closed.
