### ISSUE TITLE
Unicode version updated to v15.1 in test cases but not in source code

### ISSUE THREAD

**Issue by sid-wr** [fribidi/fribidi#204]
Hi @dov @epico @khaledhosny @behdad 

I was just looking at the Unicode version.

In the source code, it is still v`14.0` done via https://github.com/fribidi/fribidi/commit/fd00e3d236dd4d31b1c15bc8c80fbcf782a06332 in 2021

However, the Unicode version seems to be updated in only the test cases to v`15.0` via https://github.com/fribidi/fribidi/commit/df75184895dd499668f3a5cfb7b4adb13dd9698f in 2022 & followed by v`15.1` via https://github.com/fribidi/fribidi/commit/3002ffea02581b514d70c56d972af12082c4e70c in 2024

Ideally the Unicode version should be same at source code as well as test cases

Can you please get it updated ?
Thanks

**Comment by dov** [comment]
Fixed in commit e01a424c7cef4e805879ddcdc47f163f2a2f39dc . Thanks!

**Comment by sid-wr** [comment]
Thanks

**Comment by sid-wr** [comment]
@dov  Just one more thing: Do you have any plans of publishing a new FriBiDi release version anytime soon? 
As the last release was in May 2023

**Comment by dov** [comment]
@sid-wr Makes sense, but please open a separate issue requesting it.

**Comment by sid-wr** [comment]
@dov I just cross-checked your changes done in commit https://github.com/fribidi/fribidi/commit/e01a424c7cef4e805879ddcdc47f163f2a2f39dc for UCD `15.1.0` upgrade.

There are 2 files still on UCD `14.0.0`: ReadMe.txt & UnicodeData.txt

I have raised a PR https://github.com/fribidi/fribidi/pull/205 for these changes.
Please review it

Once it gets merged, I would definitely raise a separate issue for requesting a new FrIBidi version release.
Thanks

**Comment by sid-wr** [comment]
Hi @dov Can you please check this PR https://github.com/fribidi/fribidi/pull/205 once

Once it gets reviewed & merged, I would definitely raise a separate issue for requesting a new FrIBidi version release.
Thanks
