### ISSUE TITLE
Request for a new version release (April 2024)

### ISSUE THREAD

**Issue by sid-wr** [fribidi/fribidi#206]
Hi @dov  Can you please publish a new FriBiDi release version ? 
As the last release was v`1.0.13` in May 2023

Also, as a suggestion, may be you can also enable the **Discussions** tab on this repo so as to separate general user queries from  actual **Issues/Feature Requests**.
That way might be cleaner approach to avoid general user queries getting tagged as issues at your end.

E.g. GoogleTest repo also has 2 such sections:
- https://github.com/google/googletest/discussions
- https://github.com/google/googletest/issues

Thanks

**Comment by sid-wr** [comment]
Hi @dov , can you please check this. It would be much helpful
Thanks

**Comment by irfangreen** [comment]
Hi @dov @behdad, Could you please look into this.

**Comment by dov** [comment]
Done. Just released v1.0.14.

**Comment by sid-wr** [comment]
Thanks a lot @dov
