### ISSUE TITLE
Set up continuous build

### ISSUE THREAD

**Issue by behnam** [fribidi/fribidi#21]
We can set up Travis CI for continuous build. Eventually, maybe even use that for automated release.

For an evergreen master branch, we can use Bors <https://bors.tech/>, which works with Travis CI and needs minimal work to set up.

**Comment by khaledhosny** [comment]
This is mostly done (the `.travis.ci` is in place). Someone needs to log into http://travis-ci.org/ and enable the build for fribidi organization.

**Comment by dov** [comment]
What's the status of this?

**Comment by khaledhosny** [comment]
You (or @behdad) need to setup a fribidi account on http://travis-ci.org/ and enable the building of this repo.

**Comment by khaledhosny** [comment]
Looks like only the owner can do this. Also no need to setup an organization account (I was confusing Travis with AppVoyer), just create an account on http://travis-ci.org/ and enable fribidi/fribidi repository.

**Comment by dov** [comment]
Done!

**Comment by khaledhosny** [comment]
Thanks, all good now.
