### ISSUE TITLE
Old downloads changed

### ISSUE THREAD

**Issue by make-all** [fribidi/fribidi#213]
I am maintaining an older embedded project based on Yocto Linux. The platform build files reference fribidi 0.19.7 downloads from freebidi.org. In the past couple of days the nightly build has detected a checksum change in those downloads. I checked 0.19.7 release here on github, and it still has the original checksums.

Was there an intentional change?
Is the project team still in control of the fribidi.org domain?
Is the project team still active? There has been some recent activity, but there appears to be spam posts in the Issues that have not been cleaned up in over a month.

**Comment by make-all** [comment]
I've investigated further and the change in download appears to not be malicious, but the download URLs are now redirecting to the front page. I will update the build recipes and look into whether updating to use the latest version of fribidi causes any build issues since there are many fuzz issues fixed in addition to the Unicode spec updates. There is mention in the 1.0.0 release that backward compatibility was kept, but I am not sure whether it is still maintained in subsequent releases since so many years have passed.

**Comment by behdad** [comment]
Thanks for the report. The project is in maintenance mode. I don't know who owns the domain. Probably @dov.

**Comment by dov** [comment]
No, not me. I've never had any association with fribidi.org.

**Comment by behdad** [comment]
Might be @behnam then.
