### ISSUE TITLE
Versioning Policy?

### ISSUE THREAD

**Issue by behnam** [fribidi/fribidi#25]
https://github.com/fribidi/fribidi/blob/6e23ed0d4adf2e889cd593ed9ee4df3edaa3ba49/NEWS#L1-L4

I don't remember what's the versioning policy for the project, but it feels like if the change is actually backwards incompatible (broken API or change in the semantics of the API), then it should become `0.20.0`, instead of `0.19.8`.

And, now that we're on this topic, maybe it's better to fix a versioning policy?

[Semantic Versioning](http://semver.org/) is a good balance in practice, so I'd like to recommend it.

**Comment by behdad** [comment]
We decided to not break API after all.

**Comment by behnam** [comment]
Right, the changes are not breaking API here.

But, the question is: since the expected output of the function is different from what it was before (hence the "not backwards compatible" note in the NEWS file), and considering the fact that a new revision of the spec is now implemented, should it require a "minor" version bump, or a "macro" one.

**Comment by behdad** [comment]
Definitely minor. So, 0.20 or whatever.  Or call it 1!, or 3! Just don't change soname.

**Comment by khaledhosny** [comment]
I vote for 1.0.0, a major update to UBA does not happen every day, and the library is certainly mature enough for a 1.0.0 (though technically this is the 2nd major update to the library, but the major version wasn’t increased before). The soname should be kept unchanged indeed, just like HarfBuzz did.

**Comment by behnam** [comment]
Agreed. I think the library deserves a major version larger than `0` after all these years. `1.0` is an option, also `2.0`, based on what @khaledhosny said and also it goes well after `0.19.x`.

**Comment by dov** [comment]
I'm for 1.0.0, as I think it would be confusing to jump from 0.x to 2.0. But I'd like to solve issue #26 before release.

**Comment by dov** [comment]
Let's reconnect here. After fixing the cross compilation issue I think that we are ready to go for version 1.0.0. Please add your objections/approvals to issue #38 .
