### ISSUE TITLE
Missing archive files

### ISSUE THREAD

**Issue by aachkar-miovision** [fribidi/fribidi#28]
If you have a look at this recipe (https://github.com/GStreamer/cerbero/blob/master/recipes/fribidi.recipe), you'll notice that the source points to http://fribidi.org/download/fribidi-%(version)s.tar.bz2

I recently noticed when trying to build with cerbero that this file has disappeared. I tried to replace it with this archive https://github.com/fribidi/fribidi/archive/0.19.7.tar.gz, but got strange build errors. After looking at the source side by side (I happened to have a copy of the original .tar.bz2), I could see that the two archives did not contain the same content. It seems the now missing tar.bz2 was the correct archive, but I can't locate it anymore and update the recipe accordingly.

**Comment by DeadSix27** [comment]
The archive on github is just the raw source, it's not bootstrapped I think, I run into errors indicating that at least (during cross compilation):
```
./gen-unicode-version.exe ./unidata/ReadMe.txt ./unidata/BidiMirroring.txt gen-unicode-version.c > fribidi-unicode-version.h \
|| (rm -f fribidi-unicode-version.h && false)
/bin/bash: ./gen-unicode-version.exe: cannot execute binary file: Exec format error
```

**Comment by aachkar-miovision** [comment]
That's a good point. We should be able to build from the source rather than relying on the pre-bootstrapped release tarball, but I am running into an issue with how passed CFLAGS with multiple args lose their string quote blocks. I attached the cerbero logs that show the exact steps taken (see fribidi-compile.txt). I am not really sure how to go about resolving this.

[fribidi-extract.txt](https://github.com/fribidi/fribidi/files/1478531/fribidi-extract.txt)
[fribidi-configure.txt](https://github.com/fribidi/fribidi/files/1478530/fribidi-configure.txt)
[fribidi-compile.txt](https://github.com/fribidi/fribidi/files/1478529/fribidi-compile.txt)

**Comment by eli-schwartz** [comment]
Yes, in fact this whole bootstrap thing seems completely insane, see this support thread for a similar case: https://bbs.archlinux.org/viewtopic.php?id=231983

autotools projects are *supposed* to rely on `autoreconf -fi` to generate all build files for a dist tarball, rather than using custom, project-specific autogen.sh or bootstrap scripts. In the event that those files do need to be regenerated, `autoreconf -fi` will do that too. Forcing the configure script to be regenerated every time `make` is run is, well, extremely strange and I don't think I've seen anywhere else that does this.

Would you mind please explaining what issue this was even supposed to resolve in the first place? :smile:

**Comment by loqs** [comment]
https://github.com/fribidi/fribidi/blob/6c57b8a147469dafaea25a07db95962fc11063f7/Makefile.am#L34
this call to bootstrap from within make triggers https://github.com/fribidi/fribidi/blob/6c57b8a147469dafaea25a07db95962fc11063f7/bootstrap#L145
so make has called configure but without any arguments dropping any arguments from previous configure invocations.  The run through bootstrap also seems to break quoting as already mentioned.

**Comment by behdad** [comment]
When I wrote that stuff, autoreconf didn't exist :).  I confess though, I overengineered the heck out of fribidi in those years.  I've been cleaning up since...

**Comment by aachkar-miovision** [comment]
May I propose we close this issue (many projects are now using mirrors of the old release tarballs, so the "missing source archives" part is less the issue) and open a new issue to replace the bootstrap script with more conventional autogen.sh and aim for compliance with current autotools conventions.
