### ISSUE TITLE
soname has bumped to 4

### ISSUE THREAD

**Issue by behdad** [fribidi/fribidi#29]
Please change back to 0.

**Comment by dov** [comment]
Sorry. This is one of the automake engineering issues that I need to be educated above. Is this what you want?

```
m4_define(fribidi_interface_version, 0)dnl
m4_define(fribidi_interface_age, 0)dnl
m4_define(fribidi_binary_age, 0)dnl
```

Please direct me to the documentation for the above variables, and also describe the logics for the settings that you prefer.

**Comment by dov** [comment]
Oops. I just found your comments in the configure.ac file. Should I just follow the instructions for "if any functions have been added" with 0.19.7 as a baseline?
