### ISSUE TITLE
Test suite doesn't run with newer automake

### ISSUE THREAD

**Issue by behdad** [fribidi/fribidi#3]
Should copy fix idea from harfbuzz/test/shaping/Makefile.am

**Comment by khaledhosny** [comment]
Is this still an issue?

**Comment by behdad** [comment]
Not sure. If it works for you, close.

**Comment by dov** [comment]
I just a clean build on Fedora 26, with and without c2man.

1. Without c2man, fribidi "./bootstrap; ./configure; make check" builds and checks cleanly, but outputs lots of warnings about missing c2man.

2.  After cloning, configure, building, and installing https://github.com/freedesktop-unofficial-mirror/fribidi__c2man , fribidi build as above is clean without any warnings.

My automake version is 1.15 . Is this "recent enough"? Is there any other configuration that is not working?

**Comment by khaledhosny** [comment]
No issue here as well, so I think this can be closed.
