### ISSUE TITLE
configure fails with a syntax error

### ISSUE THREAD

**Issue by alyssais** [fribidi/fribidi#37]
Attempting to build on a fresh Debian or Fedora docker image with autoconf, automake, and libtool installed.

`bootstrap` succeeds, but then `configure` fails with this error:

```
./configure: line 13654: syntax error near unexpected token `GLIB,$GLIB_PACKAGE'
./configure: line 13654: `      PKG_CHECK_MODULES(GLIB,$GLIB_PACKAGE >= $GLIB_MINVERSION)'
```

This happens both on master and the latest release.

**Comment by behdad** [comment]
Looks like you didn't have pkg-config development package installed when running bootstrap...
