### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by khaledhosny** [fribidi/fribidi#38]
Are there any release blockers, anything I can help with?

**Comment by dov** [comment]
I think we are ready to go for release. So what did we decide about the release number? 0.19.8? 0.20.0? 1.0.0?

I'm for 0.20.0 .

**Comment by khaledhosny** [comment]
0.20.0 sounds good.

**Comment by dov** [comment]
I realized that I said 1.0.0 in #25 and there seemed to be a consensus, so let's go for it.

**Comment by khaledhosny** [comment]
1.0.0 is also good.
