### ISSUE TITLE
Upgrade to newer Unicode version (8.0?)

### ISSUE THREAD

**Issue by tasn** [fribidi/fribidi#4]
Hey,

It seems that fribidi currently implements 6.2. There have been a few useful additions to the Unicode algorithm since. More specifically, bidi isolates in 6.3. Please update fribidi.

**Comment by behdad** [comment]
@dov has a branch that we should merge soon.  Dov, what's the status?  Is it ready?

**Comment by dov** [comment]
The current status is with respect to 6.3 compatibility is as follows:

* Only 15 errors out of 770241 total tests in BidiTest.txt
* All the failures are overflow related, thus the chance of hitting a failure is theoretical and not practical.
* All tests in BidiCharacterTest.txt passes.
* The implementation isn't optimal, and it will do a linear scan for some rules which is very slow.
* The N0 rule hasn't been implemented (though strangely enough there does no seem to be any tests for it).
* My repo needs some love and release management to make an initial release.

Thus depending on your needs @tasn (what are they?), it might be good enough.

**Comment by tasn** [comment]
I don't really need any 8.0 features. I need the directional isolates.
Also, because of bureaucracy, I need it in a FriBidi release, not just off
Git. :)
I need it for the next version of tizen, there was a feature request to get
directional isolates working.

--
Tom.

**Comment by behdad** [comment]
I'll try to review and merge Dov's branch this week.

**Comment by tasn** [comment]
Thanks a lot.

**Comment by behdad** [comment]
Here's Dov's branch BTW: https://github.com/dov/fribidi/tree/unicode63

**Comment by behdad** [comment]
I started reviewing it but needs more work on my side...

**Comment by tasn** [comment]
Thanks for the update. Looking forward to the release.

**Comment by dov** [comment]
I have during the last week done some cleanup:

1. Fixed bugs so that fribidi now passes all the unicode test cases.
2. Got rid of non-relevant files from the repo.
3. Rebased on top of Behdad's master branch.

As far as I'm concerned, the repo is ready for release. But feel free to test it and let us know of any problems. 

The branch is still at:  https://github.com/dov/fribidi/tree/unicode63

**Comment by khaledhosny** [comment]
Anything missing for merging the unicode63 branch?

**Comment by dov** [comment]
As far as I'm concerned everything is working. But I'm waiting for Behdad's (and others'!) input. So please try to break it and open bug reports.

**Comment by behdad** [comment]
I'm finally getting back home this week and plan to spend some time on fribidi soon.  Thanks Dov amd Khaled for your patches.

**Comment by dov** [comment]
Since Unicode 10 has been fully implemented in master I'm closing this bug.
