### ISSUE TITLE
2Problem in Persian

### ISSUE THREAD

**Issue by AhmadRezaie** [fribidi/fribidi#41]
Hi.
there are 2 big problem with Persian. 

1.there is a problem with "الف" that show additional square !! in result , please check this:
"آلایندگی"

2.There is Problem with Multi Line Texts, Lines will be reversed!!!

![image](https://user-images.githubusercontent.com/35743959/35298498-9bf1e42a-0097-11e8-8083-a25674a9e1fa.png)

**Comment by dov** [comment]
This probably has nothing to do with fribidi. The reversal of the text indicates that your display engine is reordering the text again, after being handled by fribidi. Try drawing the characters one character at a time and see if the problem remains. You may want to look at the script view-chars.py in the repository/branch/path dov/dov-unicode-10:fribidi-vs-unicod/view-chars.py for a suggestion of how to draw the characters one at a time with gtk, pango, and cairo.

**Comment by khaledhosny** [comment]
For the 1st issue, looks like you are using the deprecated FriBiDi shaping API. When forming ligatures, this API will add 'ZERO WIDTH NO-BREAK SPACE' (U+FEFF) to the ligature to keep the number of output characters the same as input characters. Calling `fribidi_remove_bidi_marks` should remove these among others.

But this shaping API is deprecated for a reason; it does very limited Arabic shaping and does not make use of advanced font features and does not handle mark positioning. You should use FriBiDi for bidi algorithm, and HarfBuzz for shaping, or use a library like [Raqm](https://github.com/HOST-Oman/libraqm) that does just this in a convenient API.

For the 2nd issue, you need to break lines in the logical not visual order.

**Comment by AhmadRezaie** [comment]
thank you guys.
i have fixed my problem with line isolation & remove_bidi_marks

**Comment by khaledhosny** [comment]
This should be closed now.
