### ISSUE TITLE
Release tarball for 1.0.0?

### ISSUE THREAD

**Issue by ilovezfs** [fribidi/fribidi#44]
I'm getting a bunch of warnings about c2man being missing and am having to add Autotools dependencies to the Homebrew formula. Any chance we could get an actual release tarball for 1.0.0 to avoid this?

**Comment by khaledhosny** [comment]
c2man is required to build the main pages whether it is a release tarball or not, unfortunately finding a compatible version of c2man is tricky (I have one on my system but I always forget where I got it from). Finding an alternative to c2man should be the way forward, but that looks like a bit of work, adding an option to skip documentation generation (tracked on #8) would be an interim solution.

**Comment by khaledhosny** [comment]
I take that back, the release tarball made with `make dist` actually includes the generated man pages.

**Comment by behdad** [comment]
I had a `c2man` repo on freedesktop.org. Just pushed it to github: https://cgit.freedesktop.org/fribidi/c2man/
