### ISSUE TITLE
Upload old release tarballs to GitHub

### ISSUE THREAD

**Issue by khaledhosny** [fribidi/fribidi#49]
It would be nice of old release tarballs were uploaded to GitHub releases, just to have everything in one place.

**Comment by hfiguiere** [comment]
Where do we find the old ones since fridibi.org redirects here?

**Comment by khaledhosny** [comment]
Good question, and I have no idea myself (I wasn’t ware of the redirect either). Even more reasons to upload the tarballs here.

**Comment by hfiguiere** [comment]
The bigger problem is that the archive available https://github.com/fribidi/fribidi/archive/0.19.7/fribidi-0.19.7.tar.gz isn't the same as what was on fribidi.org, because it is a tarball generated from the tree, rather than by tarball generation `make dist`. Which cause problems.

**Comment by khaledhosny** [comment]
Yes these are the unhelpful archives that GitHub insists on generating for release tags with no way to turn it off. Just to clarify, I’m suggesting to upload the release tarballs make by make dist (like it was done for the last releases), assuming there are still available somewhere.

**Comment by behnam** [comment]
You need to go to the <https://github.com/fribidi/fribidi/releases/> page and create a "Release" for each of these old "Tags", and there you can attach tarballs to the release. It would look similar to the 1.0.0+ releases already made there. Any repo admin can do this here.

In addition to that, some projects are also maintaining their release files in its own branch (usually called `release`), which has one commit per release tag on the `master` branch. This allows to see changes of the release packages in-repo, also let GitHub create the tarball from the directory. Some repos even go further and automate this in CI, to commit to `release` per new `v*` tags on `master.

Here's an example repo: <https://github.com/adobe-fonts/source-han-serif/tree/release>

**Comment by behdad** [comment]
@behnam the question was: where can we find the old release tarballs, now that you have redirected fribidi.org to github.

**Comment by behnam** [comment]
They used to be under <https://www.fribidi.org/download/> and are now left behind on fd.o servers. I'm following up with the fd.o sys-admins to get a backup. I'll update here when I have it.

**Comment by behnam** [comment]
Also, for the record, this is last version of fribidi.org pre-migration: https://web.archive.org/web/20171109094638/https://www.fribidi.org/

**Comment by behnam** [comment]
Also, for the record, this is last version of fribidi.org pre-migration, which also has a copy of the original tarballs: <https://web.archive.org/web/20171109094638/https://www.fribidi.org/>

**Comment by hfiguiere** [comment]
If you have ssh access to "annarchy.freedesktop.org" you should be able to get them back.

**Comment by hfiguiere** [comment]
I happen to have and can see them if you need help (read only though, but it should be enough)

**Comment by hfiguiere** [comment]
(the reason I'm interested in this is because I was creating a flatpak for AbiWord).

**Comment by behnam** [comment]
Thanks, @hfiguiere. I just emailed sys-admins to update my SSH key. If it takes too long to fix, I'll ask you to help with backing up the old website. (For archival reasons, I want to put the complete website somewhere.)

**Comment by behdad** [comment]
I put a copy here: http://behdad.org/fribidi.freedesktop.org.tar.bz2

**Comment by behdad** [comment]
There's less than a handful of releases.

**Comment by khaledhosny** [comment]
Looks like only the repo owner can make GitHub releases (and upload stuff).

**Comment by khaledhosny** [comment]
I uploaded the tarballs up to 1.19.1, excluding 1.19.2 which is not tagged. Older 1.0.x series are not part of the repository history at all.

**Comment by khaledhosny** [comment]
I suppose we can close this now.
