### ISSUE TITLE
Packaging problems with release 1.0.1

### ISSUE THREAD

**Issue by bdubbs** [fribidi/fribidi#50]
There are several issues with the release tarball.

1. fribidi-1.0.1.tar.gz expands to a fribidi-0.19.7 directory.  So does fribidi-1.0.0.tar.gz.

2. There is no information about the release in the NEWS file.  The last entry is for changes between 0.19.6 and 0.19.7.

3. How do you build from the tarball?  There is no m4 directory so autoreconf does not work.  I did copy the m4 directory from the fribidi-0.19.7.tar.bz2 tarball and got it to build, but it would be better if you ran autoreconf and released that tarball.

4.  Can you please include the man pages in the tarball like in version fribidi-0.19.7.tar.bz2.  Many users do not have c2man available.

**Comment by khaledhosny** [comment]
1. There is no fribidi-1.0.1.tar.gz, where did you get it from? There [fribidi-1.0.1.tar.bz2](https://github.com/fribidi/fribidi/releases/download/v1.0.1/fribidi-1.0.1.tar.bz2) and it extracts to fribidi-1.0.1 as expected.
2. Same as above, there are entries for both 1.0 and 1.0.1 releases in the NEWS file.
3. You should not run sutoreconf in release tarball (that is standard for any package using autotools), just run the configure script directly.
4. The man pages are included.

**Comment by khaledhosny** [comment]
Ah, I guess you downloaded the archive that GitHub (un)helpfully auto-generates (I got fooled by the link being https://github.com/fribidi/fribidi/archive/v1.0.1.tar.gz but the downloaded file is indeed called fribidi-1.0.1.tar.gz) which never works with autotools (unless one commits all the generated files).

Just use fribidi-1.0.1.tar.bz2 and things should be fine.

**Comment by bdubbs** [comment]
Thanks.  That looks much better.  Builds fine.  Closing.
