### ISSUE TITLE
What FRIBIDI_NAMESPACE is for

### ISSUE THREAD

**Issue by khaledhosny** [fribidi/fribidi#60]
I have always wondered about the point of doing:
```
#define fribidi_get_bracket FRIBIDI_NAMESPACE(get_bracket)
FRIBIDI_ENTRY FriBidiBracketType fribidi_get_bracket (
…
)
```

**Comment by behdad** [comment]
I did this on request from Owen Taylor back circa 2004. Those days we didn't have hidden attribute or export symbol lists.  The idea was that the fribidi embedded in Pango could use symbol names different from the standalone fribidi library, such that apps like AbiWord that pull both in wouldn't clash their symbols.

Go ahead, remove it.

**Comment by khaledhosny** [comment]
OK, will do after #59 is merged to avoid conflicts.
