### ISSUE TITLE
E-mail address

### ISSUE THREAD

**Issue by tddpirate** [fribidi/fribidi#65]
In the THANKS file, please update my E-mail address from obsolete omerz@actcom.co.il to current w1@zak.co.il. It would be nice to grep all files to ensure that there are no leftover mentions of the obsolete E-mail address (or other obsolete E-mail addresses, for the matter).

**Comment by dov** [comment]
Fixed!

If you are aware of any other obsolete addresses. Please send pull requests or separate bug reports.
