### ISSUE TITLE
Uninitialized value in fribidi-char-sets-cap-rtl.c

### ISSUE THREAD

**Issue by khaledhosny** [fribidi/fribidi#67]
While trying to debug the spurious build failures on Travis (like [this](https://travis-ci.org/fribidi/fribidi/jobs/345700744#L3620) and [this](https://travis-ci.org/fribidi/fribidi/jobs/345285825#L3673)), I modified `run.tests` to run under valigrind and got this:
```
==31076== Conditional jump or move depends on uninitialised value(s)
==31076==    at 0x4E3E283: init_cap_rtl (fribidi-char-sets-cap-rtl.c:126)
==31076==    by 0x4E3E427: fribidi_cap_rtl_to_unicode (fribidi-char-sets-cap-rtl.c:180)
==31076==    by 0x4E3DD8B: fribidi_charset_to_unicode (fribidi-char-sets.c:160)
==31076==    by 0x109C81: main (fribidi-main.c:398)
==31076==  Uninitialised value was created by a stack allocation
==31076==    at 0x4E3E026: init_cap_rtl (fribidi-char-sets-cap-rtl.c:79)
```

Initializing the array with zeros makes this go away but I’m not sure that is the right fix and I couldn’t immediately tell what this code is trying to do.

**Comment by dov** [comment]
Fixed in 47ed4eb . (I hope I understood @behdad's intentions correctly)
