### ISSUE TITLE
Symbol FRIBIDI_TYPE_PDF_LRI is undefined

### ISSUE THREAD

**Issue by egorpugin** [fribidi/fribidi#69]
See https://github.com/fribidi/fribidi/blob/c301aaedcc9615c6c2660409b26cf6bfb6488321/lib/fribidi-bidi-types.h#L182
If this condition is not working (try to add `&& 0`), you'll get errors:
```
error C2065: 'FRIBIDI_TYPE_PDF_LRI': undeclared identifier
...
```

Following symbols become undefined:
```
# define FRIBIDI_TYPE_LRI   FRIBIDI_TYPE_PDF_LRI
# define FRIBIDI_TYPE_RLI   FRIBIDI_TYPE_PDF_RLI
# define FRIBIDI_TYPE_FSI   FRIBIDI_TYPE_PDF_FSI
# define FRIBIDI_TYPE_PDI   FRIBIDI_TYPE_PDF_PDI
```

**Comment by dov** [comment]
Fixed in 46f52d5 . Symbol definitions had cut and paste typos.
