### ISSUE TITLE
Compile gen.tab with native compiler

### ISSUE THREAD

**Issue by Kagami** [fribidi/fribidi#7]
Hi. This issue was already [reported at mail list](http://comments.gmane.org/gmane.comp.internationalization.fribidi/572) by haven't been addressed yet.

Currently it's not possible to build `gen.tab` with different compiler than for remaining sources. It becames a problem in case of cross compiling. I'm using

```
sed -i 's/^CC =.*/CC=gcc/' gen.tab/Makefile
```

hack to workaround this, but it would be nice to have it fixed.

Thanks.

**Comment by dov** [comment]
Here is a link that appear to describe a technical solution to this:

https://www.redhat.com/archives/linux-audit/2012-November/msg00000.html

**Comment by behdad** [comment]
There's some more:
https://lists.gnu.org/archive/html/autoconf/2003-09/msg00180.html
https://www.google.com/search?q=host_cc&oq=host_cc&aqs=chrome..69i57j0l5.2030j0j1&sourceid=chrome&ie=UTF-8

**Comment by dov** [comment]
This has been implemented in the build-cc branch. As an example, to cross compile for mingw64 do:

        git clean -xfd ; ./bootstrap; mingw64-configure ; make 

Please let me know of any problems.
