### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by nacho** [fribidi/fribidi#70]
There were several fixes for msvc build. Can we get a new release?

**Comment by dov** [comment]
I'll try to look to it in the next few days. Out of curiosity, what windows projects are using fribidi?

**Comment by nacho** [comment]
I saw pango now depends on fribidi. And we are building it with https://github.com/wingtk/gvsbuild

**Comment by dov** [comment]
I thought pango used an embedded mini-fribidi version. Has that been changed? If so, that is for the good, imo. One less "fork" to maintain and update?

**Comment by nacho** [comment]
I saw this commit in pango master: https://git.gnome.org/browse/pango/commit/?id=5e8cb02bec01e4a9b0ddff173889043d9db65fbc

**Comment by dov** [comment]
Great! Thanks @khaledhosny .

**Comment by nacho** [comment]
ping

**Comment by dov** [comment]
There are still some problems with the Visual Studio compilations under Windows, and I hoped that these would have been resolved. But it is really no reason not to make another release. I'll try to do it later tonight.

**Comment by dov** [comment]
Done!

**Comment by nacho** [comment]
Thanks!
