### ISSUE TITLE
run.tests script generate "multiple outputs"

### ISSUE THREAD

**Issue by dov** [fribidi/fribidi#75]
Sometimes run.tests fails the comparison between the output and the reference files. E.g. the following travis build failed because of this:

https://travis-ci.org/fribidi/fribidi/jobs/355547972

Analyzing the failure shows that the test output files contain multiple instances of **each** input row. E.g. the following is the output corresponding to the last row of test_CapRTL_explicit.input:

    this bug 67_r_o89 caught!           => this bug 6789 caught! => this bug 6789 caught!           => this bug 6789 caught! => this bug 6789 caught!           => this bug 6789 caught! => this bug 6789 caught!           => this bug 6789 caught!

This fails the comparison with the expected line:

    this bug 67_r_o89 caught!           => this bug 6789 caught!

It appears as if the output of fribidi is fed as input into the fribidd script. Is this a reference bug within the fribidi executable sources? Or perhaps some bad interaction with parallel builds? 

Whatever the case, it should be fixed to prevent spurious test failures.

**Comment by khaledhosny** [comment]
Would this by any chance related to #67?

**Comment by dov** [comment]
@khaledhosny , I very much doubt it is related to #67, as it was only a bug w.r.t. to creating the mapping between the CapRTL characters and their real unicode counterparts.

**Comment by dov** [comment]
Besides, after the above commit travis failed with the same multiple output bug in the test of test_UTF-8_persion , so it is certainly not CapRTL related.

See: https://travis-ci.org/fribidi/fribidi/builds/356193126?utm_source=email&utm_medium=notification

**Comment by dov** [comment]
This issue seems to have "disappeared". Probably it was some toolchain glitch. So I'm closing it.
