### ISSUE TITLE
meson build checks for c2man and exits

### ISSUE THREAD

**Issue by Anton-Latukha** [fribidi/fribidi#79]
Good day to you.

Autotools builds `1.0.3`.

Meson encounters:

```
configuring
meson flags: --buildtype=release         --libdir=/nix/store/nlij94sw6vfh0k9jqch4lx7a0a2cmwj1-fribidi-1.0.3/lib --libexecdir=/nix/store/nlij94sw6vfh0k9jqch4lx7a0a2cmwj1-fribidi-1.0.3/libexec         --bindir=/nix/store/nlij94sw6vfh0k9jqch4lx7a0a2cmwj1-fribidi-1.0.3/bin --sbindir=/nix/store/nlij94sw6vfh0k9jqch4lx7a0a2cmwj1-fribidi-1.0.3/sbin         --includedir=/nix/store/nlij94sw6vfh0k9jqch4lx7a0a2cmwj1-fribidi-1.0.3/include         --mandir=/nix/store/nlij94sw6vfh0k9jqch4lx7a0a2cmwj1-fribidi-1.0.3/share/man --infodir=/nix/store/nlij94sw6vfh0k9jqch4lx7a0a2cmwj1-fribidi-1.0.3/share/info         --localedir=/nix/store/nlij94sw6vfh0k9jqch4lx7a0a2cmwj1-fribidi-1.0.3/share/locale         --prefix=/nix/store/nlij94sw6vfh0k9jqch4lx7a0a2cmwj1-fribidi-1.0.3
The Meson build system
Version: 0.46.1
Source dir: /build/source
Build dir: /build/source/build
Build type: native build
Project name: fribidi
Native C compiler: /nix/store/wf4hs6m724zpbz93br1fwpl1dryas095-gcc-wrapper-7.3.0/bin/cc (gcc 7.3.0 "gcc (GCC) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Compiler for C supports arguments -ansi: YES
Compiler for C supports arguments -fvisibility=hidden: YES
Checking for function "memmove": YES
Checking for function "memset": YES
Checking for function "strdup": YES
Has header "stdlib.h": YES
Has header "string.h": YES
Has header "memory.h": YES
Has header "strings.h": YES
Has header "sys/times.h": YES
Has header "strings.h": YES
Configuring config.h using configuration
Has header "stdlib.h": YES
Has header "string.h": YES
Has header "strings.h": YES
Checking for size of "int": 4
Configuring fribidi-config.h using configuration
Program test-runner.py found: YES (/build/source/test/test-runner.py)
Program c2man found: NO

doc/meson.build:4:2: ERROR:  Problem encountered: c2man is required to build documentation. Or disable with -Ddocs=false

```

I would be glad. When it going to work I would package it with mason.

Thank you once more.

---
Additional information:
`fribidi v1.0.3` tarball
`meson 0.46.1`
`gcc 7.3.0`
`kernel 4.15.18`

**Comment by jtojnar** [comment]
@Anton-Latukha then we either need to remove `devdoc` from fribidi `outputs`, or package https://github.com/fribidi/c2man

**Comment by tp-m** [comment]
I don't entirely understand what the bug here is exactly?

Are you saying the bug is that it behaves differently than autotools because it doesn't do autodetection but instead requires you to disable it explicitly if you don't have c2man?

Meson currently doesn't have good support for auto-style options (it can be done manually with combo options, but it's a bit tedious. There's a pull request in the works which will add it soon then we can do this more nicely and it will behave like with autotools).

Having said that distros usually don't want auto behaviour anyway because it might cause packaging issues when things (deps, requirements, etc.) change.

**Comment by khaledhosny** [comment]
Autotools build checks for c2man only when it is about to build a man page, and since the release tarball includes the built man pages this check is not triggered and c2man is not required.

**Comment by jtojnar** [comment]
https://github.com/fribidi/fribidi/pull/80 would fix this, but just as dependency autodetection it is not idiomatic for Meson, neither are dist archives with prebuilt files. For that reason, https://github.com/fribidi/fribidi/pull/47 would be preferable.

**Comment by tp-m** [comment]
I don't mind either way, I just made that PR (#80) to put all options on the table in case maintainers deem it desirable.

Switching to doxygen seems like a good idea too, but that PR has been around for a while as far as I can tell.

**Comment by Anton-Latukha** [comment]
Thanks to you all.

At the end of it, I leave this open for a while, waiting for resolution.
I would close this in time and feel free to close this.
