### ISSUE TITLE
Is fribidi intended to be shared-library-only?

### ISSUE THREAD

**Issue by smcv** [fribidi/fribidi#83]
While looking into some linking-related bugs in Debian I found that fribidi is only built as a shared library, contrary to our usual policy of building both shared and static flavours.

In https://github.com/fribidi/fribidi/commit/d39b179d8de65a19390e50cfb39bb36ae193d65b#diff-67e997bcfdac55191033d57a16d1408a "Modernize autofoo a bit", @behdad changed the libtool initialization to only build shared libraries by default. Was this intended to be a policy change, making shared libraries the only supported configuration; or was it merely intended to be a change to the *default* behaviour, which the Debian maintainer of fribidi misinterpreted as a policy change?

I ask because the correct resolution for https://gitlab.gnome.org/GNOME/pango/issues/301 depends on your answer.

**Comment by behdad** [comment]
No, that's not intended.  We just change the default to be faster compile.

**Comment by smcv** [comment]
Thanks for the clarification! I've passed that information on to the Debian maintainers of fribidi.
