### ISSUE TITLE
API header uses HAVE_CONFIG_H

### ISSUE THREAD

**Issue by aelmahmoudy** [fribidi/fribidi#85]
The header file /usr/include/fribidi/fribidi-types.h, has the following:
```
#ifdef HAVE_CONFIG_H
# include <config.h>
#endif
```
this causes some applicatioms using fribidi to fail to build, if they also use 
HAVE_CONFIG_H

examples of some build failures in Debian:

https://bugs.debian.org/906418
https://bugs.debian.org/906506

**Comment by dov** [comment]
I pushed a fix for this into https://github.com/fribidi/fribidi/tree/no-config-h . As I'm not a big expert on config tools and the different environments that fribidi is running on, I'd appreciate to get some comments on these changes.

**Comment by dov** [comment]
Since I did not receive any comments, I assume all is ok, and I merged this branch into master.
