### ISSUE TITLE
How convert "visual string" to "logical string"?

### ISSUE THREAD

**Issue by ali-hardan** [fribidi/fribidi#93]
Hello.

How can un-fribidi one string?

for example, I want to convert `ﻡﻼ﻿ﺳ` to it's original text, `سلام` as logical string.

**Comment by behdad** [comment]
A good heuristic is to apply FriBidi to it again.

**Comment by ali-hardan** [comment]
Thank you for introducing `NFKD normalization`, I didn't know about it.

running NFKD normalization helps to back characters to it's logical character, for example, `\uFEB3` (ﺳ) will be `\u633`(س). but how helps to fixing `لا` problem?

**Comment by behdad** [comment]
I thought it also converts LAM-ALEF ligature, no?

**Comment by ali-hardan** [comment]
Yes converts, but not solves this issue problem. When we have a ALEF+LAM (like مخالف) and run fribidi on it, It will be LAM+ALEF (ﻢﺧﻼ﻿ﻓ). ok, now, I run NFKD normalization on it, It will: "فلاخم". I want to convert it to "مخالف", When I run fribidi on it, it will be: "ﻢﺧﻼ﻿ﻓ". When I NFKD it, it will be "مخلا﻿ف".

NFKD not helped for this. I can't back it to "مخالف".

**Comment by ali-hardan** [comment]
edited

**Comment by khaledhosny** [comment]
Run the visual string through FriBiDi again the NFKD the output
```
$ echo سلام | fribidi | fribidi | uconv -x nfkd
```

**Comment by khaledhosny** [comment]
Better yet:
```
$ echo سلام | fribidi --clean | fribidi --clean | uconv -x nfkd 
سلام
```

**Comment by ali-hardan** [comment]
@khaledhosny , Thanks.

It works good, but see output of "مخالف":
    $ echo مخالف | fribidi --clean | fribidi --clean | uconv -x nfkd 
    مخلاف

**Comment by khaledhosny** [comment]
I guess you have to manually decode the ligatures before normalizing then, there are not that many of them:
```
$ echo مخالف | fribidi --clean | fribidi --clean | sed -e "s/ﻻ/ال/g" | uconv -x nfkd
 مخالف
```
(the `sed` arguments look swapped above).

**Comment by ali-hardan** [comment]
Thank you @khaledhosny and @behdad. The issue answered.

**Comment by ali-hardan** [comment]
But it not done completely:

There are also exists issue for `zero-width non-joiner (ZWNJ)` character. for example:

    $ echo می‌دانم | fribidi --clean | fribidi --clean | sed -e "s/ﻻ/ال/g" | uconv -x nfkd
    میدانم 

Who finds or creates a way for doing it, post it here.
I suggest writing a built-in function in fribidi, to un-fribidi strings, without ALEF+LAM and ZWNJ and probably something else I do not know issues.

**Comment by ali-hardan** [comment]
Oops, without `--clean` it will not remove ZWNJ character, so the output will be correct:

    $ echo می‌دانم | fribidi | fribidi | sed -e "s/ﻻ/ال/g" | uconv -x nfkd
    می‌دانم

**Comment by ali-hardan** [comment]
But it will be good to making a way to convert "string that FriBidied with --clean" to it's original. It is possible, by code that identify letters and discovers where ZWNJ needs.

**Comment by ali-hardan** [comment]
@behdad, I didn't understand what you mean from "disable ligation". Can you explain what it is please?

**Comment by behdad** [comment]
There's a way, in code, to tell FriBidi to NOT form لا ligature.  That should fix your مخالف test case without the need for `sed`.
